language: rust
rust: nightly

# https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
  before_cache:
    - rm -rf /home/travis/.cargo/registry

branches:
  only:
    - staging
    - trying
    - master

matrix:
  fast_finish: true
  allow_failures:
    - name: coverage
  include:
    - name: coverage
      rust: nightly-2019-05-20
      sudo: required
      cache: cargo
      env: RUSTFLAGS="--cfg procmacro2_semver_exempt" RUST_BACKTRACE=1
      addons:
        apt:
          packages:
            - libssl-dev
      install:
        - cargo install cargo-update || true
        - cargo install-update -i cargo-tarpaulin cargo-update
      script:
        - cargo tarpaulin --out Xml
      after_success:
        - bash <(curl -s https://codecov.io/bash)
