name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run tests
        run: cargo test --all-features --all-targets --no-fail-fast

  # Versions before Unpin; can't check tests which statically check Unpin OIBIT
  msrv-low:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Create lockfile
        run: cargo +nightly generate-lockfile -Zminimal-versions

      - name: Install 1.16 toolchain
        uses: dtolnay/rust-toolchain@1.16

      - name: Check
        run: cargo +1.16.0 check

  # Versions after Unpin; check tests which statically check Unpin OIBIT
  msrv-high:
    runs-on: ubuntu-latest
    env:
      TRYBUILD: overwrite
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Create lockfile
        run: cargo +nightly generate-lockfile -Zminimal-versions

      - name: Install 1.33 toolchain
        uses: dtolnay/rust-toolchain@1.33

      - name: Run tests
        run: cargo +1.33.0 test --all-features --lib --no-fail-fast
