name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run tests
        run: cargo test --all-features --all-targets --no-fail-fast

  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install 1.55 toolchain
        uses: dtolnay/rust-toolchain@1.55

      - name: Run tests
        run: cargo test --all-features --all-targets --no-fail-fast
